version: '3'
services:
  milkbot:
    build:
      dockerfile: ./.ci/Dockerfile.test
      context: ../
    environment:
      DYNAMODB_ENDPOINT: http://localstack:4566
    depends_on:
      - localstack
  localstack:
    image: 263652615682.dkr.ecr.eu-central-1.amazonaws.com/milkman/localstack:0.11.5
    environment:
      - SERVICES=dynamodb
    ports:
      - 4566:4566
